CREATE TABLE "DailyReport" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "dateLocal" TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "call1Json" JSON NOT NULL,
  "call2Json" JSON NOT NULL
);
